### ISSUE TITLE
How to authorize in docker registry?

### ISSUE THREAD

**Issue by slavniyteo** [mkdym/docker-registry-viewer#1]
Hi, I try your viewer.
But I can not find how to authorize at registry? 
Viewer shows me page with "{401 Unauthorized} (it is expected, registry needs authorization)

**Comment by mkdym** [comment]
sorry, not implemented. this is a simple registry viewer

**Comment by slavniyteo** [comment]
So sad. I see, it will stay simple, so close it.

**Comment by slavniyteo** [comment]
Today I looked at you viewer again.
Today I had tried to set env `REGISTRY_HOST=user:password@hostname` and it works =)
Why didn't I try it that time?
